### ISSUE TITLE
Access private keys of certificates

### ISSUE THREAD

**Issue by bgusach** [tiran/wincertstore#3]
Hi there, 

this is a half a question, half an issue. I'd like to fetch certificates in "MY" and their respective private keys. As far as I can tell, this is not possible. Am I wrong? if so, could it be implemented? (I could give it a try if I get some hints on how to do it).

**Comment by tiran** [comment]
This project is retired and no longer maintained.

I suggest that you study the MSDN docs and figure out how to access private keys with crypt32 API.
